# Generated by Django 4.0.2 on 2022-05-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0002_facturaenc_facturadet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de Supervisor de Caja Encabezado')], 'verbose_name': 'Encabezado Factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
