# Generated by Django 4.0.2 on 2022-05-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_alter_facturaenc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de Supervisor de Caja Detalle')], 'verbose_name': 'Detalle Factura', 'verbose_name_plural': 'Detalles Facturas'},
        ),
    ]
